import {
  Ingredient,
  IngredientId,
  Recipe,
  RecipeId,
  CustomerType,
  ShopUpgrade,
  Employee,
  GameSaveState,
  ShopTheme,
  DecorationItem,
} from './types';

export const INGREDIENTS: Record<IngredientId, Ingredient> = {
  bread: {
    id: 'bread',
    name: 'Bánh Mì Giòn',
    icon: '🥖',
    category: 'bakery',
    cost: 3000,
    description: 'Vỏ giòn rụm, ruột mềm thơm mùi bơ.',
  },
  egg: {
    id: 'egg',
    name: 'Trứng Gà Tươi',
    icon: '🥚',
    category: 'meat',
    cost: 4000,
    description: 'Trứng gà ta lòng đỏ béo ngậy.',
  },
  pork: {
    id: 'pork',
    name: 'Thịt Nướng Ướp Vị',
    icon: '🥩',
    category: 'meat',
    cost: 10000,
    description: 'Thịt heo tươi ướp sả ớt mật ong đậm đà.',
  },
  pate: {
    id: 'pate',
    name: 'Patê Gan Thơm Béo',
    icon: '🧈',
    category: 'meat',
    cost: 6000,
    description: 'Patê gan béo ngậy gia truyền.',
  },
  cucumber: {
    id: 'cucumber',
    name: 'Dưa Leo Giòn',
    icon: '🥒',
    category: 'veg',
    cost: 2000,
    description: 'Dưa leo vườn tươi mát, giải ngấy.',
  },
  herb: {
    id: 'herb',
    name: 'Rau Thơm & Ngò Gai',
    icon: '🌿',
    category: 'veg',
    cost: 1500,
    description: 'Rau ngò thơm phức chuẩn vị bánh mì Việt.',
  },
  tea: {
    id: 'tea',
    name: 'Trà Lài Hảo Hạng',
    icon: '🍃',
    category: 'beverage',
    cost: 5000,
    description: 'Lá trà ướp hoa lài thanh mát.',
  },
  milk: {
    id: 'milk',
    name: 'Sữa Tươi Thanh Trùng',
    icon: '🥛',
    category: 'beverage',
    cost: 6000,
    description: 'Sữa tươi béo ngậy ngọt lành.',
  },
  condensed_milk: {
    id: 'condensed_milk',
    name: 'Sữa Đặc Ngọt Ngào',
    icon: '🍯',
    category: 'beverage',
    cost: 4000,
    description: 'Sữa đặc béo ngọt sánh mịn.',
  },
  coffee: {
    id: 'coffee',
    name: 'Cà Phê Phin Robusta',
    icon: '☕',
    category: 'beverage',
    cost: 7000,
    description: 'Cà phê rang xay đậm đà hương vị truyền thống.',
  },
};

export const RECIPES: Record<RecipeId, Recipe> = {
  banh_mi_trung: {
    id: 'banh_mi_trung',
    name: 'Bánh Mì Trứng Ốp La',
    icon: '🍳',
    category: 'food',
    requiredIngredients: ['bread', 'egg', 'cucumber'],
    cookingTimeMs: 2500,
    basePrice: 18000,
    expGain: 15,
    description: 'Bánh mì kẹp 2 trứng ốp la lòng đào kèm dưa leo giòn rụm.',
  },
  banh_mi_thit: {
    id: 'banh_mi_thit',
    name: 'Bánh Mì Thịt Nướng',
    icon: '🥪',
    category: 'food',
    requiredIngredients: ['bread', 'pork', 'cucumber', 'herb'],
    cookingTimeMs: 3500,
    basePrice: 28000,
    expGain: 25,
    description: 'Thịt xiên nướng thơm lừng kết hợp rau thơm và dưa chua.',
  },
  banh_mi_dac_biet: {
    id: 'banh_mi_dac_biet',
    name: 'Bánh Mì Thập Cẩm Đặc Biệt',
    icon: '🥖',
    category: 'food',
    requiredIngredients: ['bread', 'pork', 'egg', 'pate', 'cucumber', 'herb'],
    cookingTimeMs: 4500,
    basePrice: 42000,
    expGain: 40,
    description: 'Món "best-seller" ngập tràn patê béo ngậy, thịt nướng và trứng ốp la.',
  },
  tra_sua: {
    id: 'tra_sua',
    name: 'Trà Sữa Cozy Signature',
    icon: '🧋',
    category: 'drink',
    requiredIngredients: ['tea', 'milk', 'condensed_milk'],
    cookingTimeMs: 2000,
    basePrice: 25000,
    expGain: 20,
    description: 'Trà sữa thơm nồng vị trà lài, ngậy béo sữa tươi.',
  },
  cafe_sua: {
    id: 'cafe_sua',
    name: 'Cà Phê Sữa Đá Sài Gòn',
    icon: '🥤',
    category: 'drink',
    requiredIngredients: ['coffee', 'condensed_milk'],
    cookingTimeMs: 2000,
    basePrice: 22000,
    expGain: 20,
    description: 'Đậm đà vị cà phê phin hòa quyện cùng sữa đặc ngọt béo.',
  },
};

export const CUSTOMER_TYPES: Record<string, CustomerType> = {
  student: {
    id: 'student',
    name: 'Bạn Học Sinh / Sinh Viên',
    description: 'Rất thích đồ ăn nhanh, trà sữa ngọt ngào và giá cả phải chăng.',
    spriteKey: 'customer_student',
    patienceSeconds: 35,
    tipRate: 0.05,
    favoriteRecipeIds: ['banh_mi_trung', 'tra_sua'],
  },
  office_worker: {
    id: 'office_worker',
    name: 'Anh Chị Dân Văn Phòng',
    description: 'Cần nạp năng lượng nhanh vào buổi sáng, chuộng cà phê sữa đá.',
    spriteKey: 'customer_office',
    patienceSeconds: 25,
    tipRate: 0.15,
    favoriteRecipeIds: ['cafe_sua', 'banh_mi_thit'],
  },
  food_lover: {
    id: 'food_lover',
    name: 'Tín Đồ Ẩm Thực',
    description: 'Sẵn sàng chờ đợi để thưởng thức bánh mì đặc biệt nhiều topping.',
    spriteKey: 'customer_gourmet',
    patienceSeconds: 45,
    tipRate: 0.25,
    favoriteRecipeIds: ['banh_mi_dac_biet'],
  },
  neighborhood: {
    id: 'neighborhood',
    name: 'Bác Hàng Xóm Thân Thiện',
    description: 'Khách quen tính tình vui vẻ, thích ngồi chill thưởng trà hoặc ăn sáng.',
    spriteKey: 'customer_neighbor',
    patienceSeconds: 50,
    tipRate: 0.1,
    favoriteRecipeIds: ['banh_mi_trung', 'cafe_sua', 'tra_sua'],
  },
};

export const SHOP_UPGRADES: ShopUpgrade[] = [
  {
    id: 'extra_table_1',
    name: 'Bàn Gỗ Sồi Cozy (Bàn 3)',
    icon: '🪑',
    description: 'Thêm 1 bàn phục vụ khách, giúp đón tiếp thêm nhiều khách cùng lúc.',
    cost: 150000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'add_table', value: 1 },
  },
  {
    id: 'extra_table_2',
    name: 'Bàn Gỗ Sồi Cozy (Bàn 4)',
    icon: '🪑',
    description: 'Thêm bàn thứ 4 cho quán, tăng doanh thu giờ cao điểm.',
    cost: 350000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'add_table', value: 1 },
  },
  {
    id: 'modern_stove',
    name: 'Bếp Nướng Điện Cao Cấp',
    icon: '⚡',
    description: 'Nhiệt độ ổn định, giảm 30% thời gian nấu món.',
    cost: 200000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'cook_speed', value: 0.3 },
  },
  {
    id: 'cozy_storage',
    name: 'Tủ Kho Bảo Quản Lớn',
    icon: '📦',
    description: 'Tăng sức chứa kho thêm 30 đơn vị nguyên liệu.',
    cost: 120000,
    level: 0,
    maxLevel: 2,
    effect: { type: 'storage_capacity', value: 30 },
  },
  {
    id: 'flower_signboard',
    name: 'Biển Hiệu Hoa Hồng Pastel',
    icon: '🌸',
    description: 'Biển hiệu lung linh dễ thương, tăng 25% tần suất khách ghé thăm.',
    cost: 250000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'attract_customers', value: 0.25 },
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp_mai',
    name: 'Bé Mai',
    role: 'server',
    careerTier: 'junior',
    avatar: '👧',
    personality: 'hardworking',
    personalityDesc: 'Chăm chỉ, cần mẫn, luôn hoàn thành nhiệm vụ trước thời hạn.',
    salaryPerDay: 45000,
    speed: 1.25,
    cookingSkill: 40,
    serviceSkill: 85,
    mood: 90,
    stress: 15,
    loyalty: 80,
    experience: 120,
    hired: false,
    description: 'Tự động mang món ăn ra bàn ngay khi bếp hoàn thành.',
  },
  {
    id: 'emp_linh',
    name: 'Bác Linh',
    role: 'cook',
    careerTier: 'senior',
    avatar: '👨‍🍳',
    personality: 'friendly',
    personalityDesc: 'Thân thiện, tỉ mỉ, nấu ăn bằng cả trái tim và tình yêu ẩm thực.',
    salaryPerDay: 65000,
    speed: 1.1,
    cookingSkill: 92,
    serviceSkill: 50,
    mood: 85,
    stress: 20,
    loyalty: 85,
    experience: 350,
    hired: false,
    description: 'Tự động chuẩn bị và chế biến món ăn khi có order của khách.',
  },
  {
    id: 'emp_tuan',
    name: 'Em Tuấn',
    role: 'cook',
    careerTier: 'intern',
    avatar: '🧑‍🍳',
    personality: 'creative',
    personalityDesc: 'Sáng tạo, thích đổi mới công thức, giúp món ăn đậm vị hơn (+15% tiền tip).',
    salaryPerDay: 50000,
    speed: 1.15,
    cookingSkill: 75,
    serviceSkill: 60,
    mood: 95,
    stress: 10,
    loyalty: 70,
    experience: 80,
    hired: false,
    description: 'Phụ bếp năng động, tăng tỷ lệ nhận thêm tiền boa từ khách.',
  },
  {
    id: 'emp_lan',
    name: 'Chị Lan',
    role: 'manager',
    careerTier: 'shift_leader',
    avatar: '👩‍💼',
    personality: 'ambitious',
    personalityDesc: 'Cầu tiến, có óc tổ chức, giúp cả tiệm giảm 25% độ căng thẳng.',
    salaryPerDay: 75000,
    speed: 1.3,
    cookingSkill: 65,
    serviceSkill: 90,
    mood: 80,
    stress: 25,
    loyalty: 75,
    experience: 280,
    hired: false,
    description: 'Trợ lý quản lý cửa hàng, hỗ trợ điều phối và tăng hiệu suất làm việc.',
  },
  {
    id: 'emp_huy',
    name: 'Cậu Huy',
    role: 'server',
    careerTier: 'intern',
    avatar: '👦',
    personality: 'extrovert',
    personalityDesc: 'Hoạt bát, vui vẻ, nụ cười tỏa nắng thu hút thêm 15% lượng khách.',
    salaryPerDay: 40000,
    speed: 1.2,
    cookingSkill: 35,
    serviceSkill: 88,
    mood: 92,
    stress: 12,
    loyalty: 72,
    experience: 60,
    hired: false,
    description: 'Phục vụ vui tươi, làm khách hàng luôn cảm thấy ấm áp.',
  },
];

export const SHOP_THEMES: Record<string, ShopTheme> = {
  sakura_pink: {
    id: 'sakura_pink',
    name: 'Hoa Anh Đào (Sakura Pink)',
    description: 'Tông màu hồng pastel ngọt ngào, ấm áp nguyên bản của tiệm.',
    primaryColor: '#F7A8C4',
    accentColor: '#FFD6E5',
    bgColor: '#FAF5EE',
    unlocked: true,
    cost: 0,
  },
  mint_cafe: {
    id: 'mint_cafe',
    name: 'Bạc Hà Dịu Mát (Mint Cafe)',
    description: 'Sắc xanh bạc hà thanh mát, tạo cảm giác thư thái dễ chịu cho khách ghé thăm.',
    primaryColor: '#72C2A1',
    accentColor: '#BFE3D0',
    bgColor: '#F3FAF6',
    unlocked: false,
    cost: 80000,
  },
  cream_bakery: {
    id: 'cream_bakery',
    name: 'Tiệm Bánh Bơ Sữa (Cream Bakery)',
    description: 'Phong cách tiệm bánh châu Âu cổ điển với màu vàng bơ và nâu cà phê ấm cúng.',
    primaryColor: '#E6A15C',
    accentColor: '#FFE6A7',
    bgColor: '#FFFBF2',
    unlocked: false,
    cost: 120000,
  },
  lavender_dream: {
    id: 'lavender_dream',
    name: 'Giấc Mơ Oải Hương (Lavender Dream)',
    description: 'Tím mộng mơ lãng mạn, mang hương thơm hoa cỏ êm dịu giữa lòng phố.',
    primaryColor: '#B39DDB',
    accentColor: '#D8C4F1',
    bgColor: '#F8F5FC',
    unlocked: false,
    cost: 180000,
  },
};

export const DECORATION_ITEMS: DecorationItem[] = [
  {
    id: 'deco_flower_vase',
    name: 'Bình Hoa Linh Lan Trắng',
    category: 'plant',
    icon: '💐',
    cost: 35000,
    cozyPoints: 12,
    bonusEffectDesc: '+5% độ kiên nhẫn của khách hàng khi chờ món.',
    owned: false,
    equipped: false,
    description: 'Hoa linh lan tượng trưng cho sự thuần khiết và may mắn.',
  },
  {
    id: 'deco_sun_lamp',
    name: 'Đèn Chùm Giọt Nắng Pastel',
    category: 'lighting',
    icon: '💡',
    cost: 55000,
    cozyPoints: 20,
    bonusEffectDesc: '+10% tỷ lệ khách hàng ghé thăm tiệm.',
    owned: false,
    equipped: false,
    description: 'Ánh sáng vàng ấm áp tạo bầu không khí lung linh lãng mạn.',
  },
  {
    id: 'deco_menu_chalk',
    name: 'Bảng Menu Vẽ Phấn Nghệ Thuật',
    category: 'wall',
    icon: '📋',
    cost: 45000,
    cozyPoints: 15,
    bonusEffectDesc: '+8% tiền boa (Tip) từ khách hàng.',
    owned: false,
    equipped: false,
    description: 'Bảng vẽ tay xinh xắn ghi lại những món "best-seller" của quán.',
  },
  {
    id: 'deco_sofa',
    name: 'Ghế Băng Chờ Bọc Nhung Hồng',
    category: 'furniture',
    icon: '🛋️',
    cost: 85000,
    cozyPoints: 30,
    bonusEffectDesc: '+15% độ kiên nhẫn tối đa cho toàn bộ khách trong tiệm.',
    owned: false,
    equipped: false,
    description: 'Khách hàng có thể ngồi nghỉ chân thư giãn khi đợi món mang về.',
  },
  {
    id: 'deco_cat_painting',
    name: 'Tranh Treo Mèo Con Thưởng Trà',
    category: 'wall',
    icon: '🖼️',
    cost: 65000,
    cozyPoints: 22,
    bonusEffectDesc: 'Giảm 20% tốc độ tăng căng thẳng (Stress) cho nhân viên.',
    owned: false,
    equipped: false,
    description: 'Bức tranh dễ thương làm tan biến mọi mệt mỏi trong ca làm việc.',
  },
];

export const INITIAL_GAME_STATE: GameSaveState = {
  version: '0.3.0',
  playerId: 'player_default',
  shopName: 'Tiệm Bánh Mì Của Tôi 🌸',
  day: 1,
  gameTimeMinutes: 360, // 06:00 sáng
  money: 100000, // 100,000 VND vốn khởi nghiệp
  reputation: 10,
  player: {
    name: 'Chủ Quán Dễ Thương',
    energy: 100,
    maxEnergy: 100,
    cookingLevel: 1,
    cookingExp: 0,
  },
  inventory: {
    bread: 10,
    egg: 6,
    pork: 4,
    cucumber: 8,
    pate: 2,
    herb: 5,
    tea: 6,
    milk: 6,
    condensed_milk: 6,
    coffee: 6,
  },
  unlockedRecipes: ['banh_mi_trung', 'banh_mi_thit', 'tra_sua', 'cafe_sua'],
  purchasedUpgrades: {},
  hiredEmployees: [],
  employeeDetails: {},
  activeTheme: 'sakura_pink',
  ownedThemes: ['sakura_pink'],
  ownedDecorations: [],
  equippedDecorations: [],
  storageCapacity: 60,
  historySummaries: [],
  lastSavedAt: new Date().toISOString(),
};

