import {
  Ingredient,
  IngredientId,
  Recipe,
  RecipeId,
  CustomerType,
  ShopUpgrade,
  Employee,
  GameSaveState,
  ShopTheme,
  DecorationItem,
} from './types';

export const INGREDIENTS: Record<IngredientId, Ingredient> = {
  bread: {
    id: 'bread',
    name: 'Bánh Mì Giòn',
    icon: '🥖',
    category: 'bakery',
    cost: 3000,
    description: 'Vỏ giòn rụm, ruột mềm thơm mùi bơ.',
  },
  egg: {
    id: 'egg',
    name: 'Trứng Gà Tươi',
    icon: '🥚',
    category: 'meat',
    cost: 4000,
    description: 'Trứng gà ta lòng đỏ béo ngậy.',
  },
  pork: {
    id: 'pork',
    name: 'Thịt Nướng Ướp Vị',
    icon: '🥩',
    category: 'meat',
    cost: 10000,
    description: 'Thịt heo tươi ướp sả ớt mật ong đậm đà.',
  },
  pate: {
    id: 'pate',
    name: 'Patê Gan Thơm Béo',
    icon: '🧈',
    category: 'meat',
    cost: 6000,
    description: 'Patê gan béo ngậy gia truyền.',
  },
  cucumber: {
    id: 'cucumber',
    name: 'Dưa Leo Giòn',
    icon: '🥒',
    category: 'veg',
    cost: 2000,
    description: 'Dưa leo vườn tươi mát, giải ngấy.',
  },
  herb: {
    id: 'herb',
    name: 'Rau Thơm & Ngò Gai',
    icon: '🌿',
    category: 'veg',
    cost: 1500,
    description: 'Rau ngò thơm phức chuẩn vị bánh mì Việt.',
  },
  tea: {
    id: 'tea',
    name: 'Trà Lài Hảo Hạng',
    icon: '🍃',
    category: 'beverage',
    cost: 5000,
    description: 'Lá trà ướp hoa lài thanh mát.',
  },
  milk: {
    id: 'milk',
    name: 'Sữa Tươi Thanh Trùng',
    icon: '🥛',
    category: 'beverage',
    cost: 6000,
    description: 'Sữa tươi béo ngậy ngọt lành.',
  },
  condensed_milk: {
    id: 'condensed_milk',
    name: 'Sữa Đặc Ngọt Ngào',
    icon: '🍯',
    category: 'beverage',
    cost: 4000,
    description: 'Sữa đặc béo ngọt sánh mịn.',
  },
  coffee: {
    id: 'coffee',
    name: 'Cà Phê Phin Robusta',
    icon: '☕',
    category: 'beverage',
    cost: 7000,
    description: 'Cà phê rang xay đậm đà hương vị truyền thống.',
  },
};

export const RECIPES: Record<RecipeId, Recipe> = {
  banh_mi_trung: {
    id: 'banh_mi_trung',
    name: 'Bánh Mì Trứng Ốp La',
    icon: '🍳',
    category: 'food',
    requiredIngredients: ['bread', 'egg', 'cucumber'],
    cookingTimeMs: 2500,
    basePrice: 18000,
    expGain: 15,
    description: 'Bánh mì kẹp 2 trứng ốp la lòng đào kèm dưa leo giòn rụm.',
  },
  banh_mi_thit: {
    id: 'banh_mi_thit',
    name: 'Bánh Mì Thịt Nướng',
    icon: '🥪',
    category: 'food',
    requiredIngredients: ['bread', 'pork', 'cucumber', 'herb'],
    cookingTimeMs: 3500,
    basePrice: 28000,
    expGain: 25,
    description: 'Thịt xiên nướng thơm lừng kết hợp rau thơm và dưa chua.',
  },
  banh_mi_dac_biet: {
    id: 'banh_mi_dac_biet',
    name: 'Bánh Mì Thập Cẩm Đặc Biệt',
    icon: '🥖',
    category: 'food',
    requiredIngredients: ['bread', 'pork', 'egg', 'pate', 'cucumber', 'herb'],
    cookingTimeMs: 4500,
    basePrice: 42000,
    expGain: 40,
    description: 'Món "best-seller" ngập tràn patê béo ngậy, thịt nướng và trứng ốp la.',
  },
  tra_sua: {
    id: 'tra_sua',
    name: 'Trà Sữa Cozy Signature',
    icon: '🧋',
    category: 'drink',
    requiredIngredients: ['tea', 'milk', 'condensed_milk'],
    cookingTimeMs: 2000,
    basePrice: 25000,
    expGain: 20,
    description: 'Trà sữa thơm nồng vị trà lài, ngậy béo sữa tươi.',
  },
  cafe_sua: {
    id: 'cafe_sua',
    name: 'Cà Phê Sữa Đá Sài Gòn',
    icon: '🥤',
    category: 'drink',
    requiredIngredients: ['coffee', 'condensed_milk'],
    cookingTimeMs: 2000,
    basePrice: 22000,
    expGain: 20,
    description: 'Đậm đà vị cà phê phin hòa quyện cùng sữa đặc ngọt béo.',
  },
};

export const CUSTOMER_TYPES: Record<string, CustomerType> = {
  student: {
    id: 'student',
    name: 'Bạn Học Sinh / Sinh Viên',
    description: 'Rất thích đồ ăn nhanh, trà sữa ngọt ngào và giá cả phải chăng.',
    spriteKey: 'customer_student',
    patienceSeconds: 35,
    tipRate: 0.05,
    favoriteRecipeIds: ['banh_mi_trung', 'tra_sua'],
  },
  office_worker: {
    id: 'office_worker',
    name: 'Anh Chị Dân Văn Phòng',
    description: 'Cần nạp năng lượng nhanh vào buổi sáng, chuộng cà phê sữa đá.',
    spriteKey: 'customer_office',
    patienceSeconds: 25,
    tipRate: 0.15,
    favoriteRecipeIds: ['cafe_sua', 'banh_mi_thit'],
  },
  food_lover: {
    id: 'food_lover',
    name: 'Tín Đồ Ẩm Thực',
    description: 'Sẵn sàng chờ đợi để thưởng thức bánh mì đặc biệt nhiều topping.',
    spriteKey: 'customer_gourmet',
    patienceSeconds: 45,
    tipRate: 0.25,
    favoriteRecipeIds: ['banh_mi_dac_biet'],
  },
  neighborhood: {
    id: 'neighborhood',
    name: 'Bác Hàng Xóm Thân Thiện',
    description: 'Khách quen tính tình vui vẻ, thích ngồi chill thưởng trà hoặc ăn sáng.',
    spriteKey: 'customer_neighbor',
    patienceSeconds: 50,
    tipRate: 0.1,
    favoriteRecipeIds: ['banh_mi_trung', 'cafe_sua', 'tra_sua'],
  },
};

export const SHOP_UPGRADES: ShopUpgrade[] = [
  {
    id: 'extra_table_1',
    name: 'Bàn Gỗ Sồi Cozy (Bàn 3)',
    icon: '🪑',
    description: 'Thêm 1 bàn phục vụ khách, giúp đón tiếp thêm nhiều khách cùng lúc.',
    cost: 150000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'add_table', value: 1 },
  },
  {
    id: 'extra_table_2',
    name: 'Bàn Gỗ Sồi Cozy (Bàn 4)',
    icon: '🪑',
    description: 'Thêm bàn thứ 4 cho quán, tăng doanh thu giờ cao điểm.',
    cost: 350000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'add_table', value: 1 },
  },
  {
    id: 'modern_stove',
    name: 'Bếp Nướng Điện Cao Cấp',
    icon: '⚡',
    description: 'Nhiệt độ ổn định, giảm 30% thời gian nấu món.',
    cost: 200000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'cook_speed', value: 0.3 },
  },
  {
    id: 'cozy_storage',
    name: 'Tủ Kho Bảo Quản Lớn',
    icon: '📦',
    description: 'Tăng sức chứa kho thêm 30 đơn vị nguyên liệu.',
    cost: 120000,
    level: 0,
    maxLevel: 2,
    effect: { type: 'storage_capacity', value: 30 },
  },
  {
    id: 'flower_signboard',
    name: 'Biển Hiệu Hoa Hồng Pastel',
    icon: '🌸',
    description: 'Biển hiệu lung linh dễ thương, tăng 25% tần suất khách ghé thăm.',
    cost: 250000,
    level: 0,
    maxLevel: 1,
    effect: { type: 'attract_customers', value: 0.25 },
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp_mai',
    name: 'Bé Mai',
    role: 'server',
    careerTier: 'junior',
    avatar: '👧',
    personality: 'hardworking',
    personalityDesc: 'Chăm chỉ, cần mẫn, luôn hoàn thành nhiệm vụ trước thời hạn.',
    salaryPerDay: 45000,
    speed: 1.25,
    cookingSkill: 40,
    serviceSkill: 85,
    mood: 90,
    stress: 15,
    loyalty: 80,
    experience: 120,
    hired: false,
    description: 'Tự động mang món ăn ra bàn ngay khi bếp hoàn thành.',
  },
  {
    id: 'emp_linh',
    name: 'Bác Linh',
    role: 'cook',
    careerTier: 'senior',
    avatar: '👨‍🍳',
    personality: 'friendly',
    personalityDesc: 'Thân thiện, tỉ mỉ, nấu ăn bằng cả trái tim và tình yêu ẩm thực.',
    salaryPerDay: 65000,
    speed: 1.1,
    cookingSkill: 92,
    serviceSkill: 50,
    mood: 85,
    stress: 20,
    loyalty: 85,
    experience: 350,
    hired: false,
    description: 'Tự động chuẩn bị và chế biến món ăn khi có order của khách.',
  },
  {
    id: 'emp_tuan',
    name: 'Em Tuấn',
    role: 'cook',
    careerTier: 'intern',
    avatar: '🧑‍🍳',
    personality: 'creative',
    personalityDesc: 'Sáng tạo, thích đổi mới công thức, giúp món ăn đậm vị hơn (+15% tiền tip).',
    salaryPerDay: 50000,
    speed: 1.15,
    cookingSkill: 75,
    serviceSkill: 60,
    mood: 95,
    stress: 10,
    loyalty: 70,
    experience: 80,
    hired: false,
    description: 'Phụ bếp năng động, tăng tỷ lệ nhận thêm tiền boa từ khách.',
  },
  {
    id: 'emp_lan',
    name: 'Chị Lan',
    role: 'manager',
    careerTier: 'shift_leader',
    avatar: '👩‍💼',
    personality: 'ambitious',
    personalityDesc: 'Cầu tiến, có óc tổ chức, giúp cả tiệm giảm 25% độ căng thẳng.',
    salaryPerDay: 75000,
    speed: 1.3,
    cookingSkill: 65,
    serviceSkill: 90,
    mood: 80,
    stress: 25,
    loyalty: 75,
    experience: 280,
    hired: false,
    description: 'Trợ lý quản lý cửa hàng, hỗ trợ điều phối và tăng hiệu suất làm việc.',
  },
  {
    id: 'emp_huy',
    name: 'Cậu Huy',
    role: 'server',
    careerTier: 'intern',
    avatar: '👦',
    personality: 'extrovert',
    personalityDesc: 'Hoạt bát, vui vẻ, nụ cười tỏa nắng thu hút thêm 15% lượng khách.',
    salaryPerDay: 40000,
    speed: 1.2,
    cookingSkill: 35,
    serviceSkill: 88,
    mood: 92,
    stress: 12,
    loyalty: 72,
    experience: 60,
    hired: false,
    description: 'Phục vụ vui tươi, làm khách hàng luôn cảm thấy ấm áp.',
  },
];

export const SHOP_THEMES: Record<string, ShopTheme> = {
  sakura_pink: {
    id: 'sakura_pink',
    name: 'Hoa Anh Đào (Sakura Pink)',
    description: 'Tông màu hồng pastel ngọt ngào, ấm áp nguyên bản của tiệm.',
    primaryColor: '#F7A8C4',
    accentColor: '#FFD6E5',
    bgColor: '#FAF5EE',
    unlocked: true,
    cost: 0,
  },
  mint_cafe: {
    id: 'mint_cafe',
    name: 'Bạc Hà Dịu Mát (Mint Cafe)',
    description: 'Sắc xanh bạc hà thanh mát, tạo cảm giác thư thái dễ chịu cho khách ghé thăm.',
    primaryColor: '#72C2A1',
    accentColor: '#BFE3D0',
    bgColor: '#F3FAF6',
    unlocked: false,
    cost: 80000,
  },
  cream_bakery: {
    id: 'cream_bakery',
    name: 'Tiệm Bánh Bơ Sữa (Cream Bakery)',
    description: 'Phong cách tiệm bánh châu Âu cổ điển với màu vàng bơ và nâu cà phê ấm cúng.',
    primaryColor: '#E6A15C',
    accentColor: '#FFE6A7',
    bgColor: '#FFFBF2',
    unlocked: false,
    cost: 120000,
  },
  lavender_dream: {
    id: 'lavender_dream',
    name: 'Giấc Mơ Oải Hương (Lavender Dream)',
    description: 'Tím mộng mơ lãng mạn, mang hương thơm hoa cỏ êm dịu giữa lòng phố.',
    primaryColor: '#B39DDB',
    accentColor: '#D8C4F1',
    bgColor: '#F8F5FC',
    unlocked: false,
    cost: 180000,
  },
};

export const DECORATION_ITEMS: DecorationItem[] = [
  {
    id: 'deco_flower_vase',
    name: 'Bình Hoa Linh Lan Trắng',
    category: 'plant',
    icon: '💐',
    cost: 35000,
    cozyPoints: 12,
    bonusEffectDesc: '+5% độ kiên nhẫn của khách hàng khi chờ món.',
    owned: false,
    equipped: false,
    description: 'Hoa linh lan tượng trưng cho sự thuần khiết và may mắn.',
  },
  {
    id: 'deco_sun_lamp',
    name: 'Đèn Chùm Giọt Nắng Pastel',
    category: 'lighting',
    icon: '💡',
    cost: 55000,
    cozyPoints: 20,
    bonusEffectDesc: '+10% tỷ lệ khách hàng ghé thăm tiệm.',
    owned: false,
    equipped: false,
    description: 'Ánh sáng vàng ấm áp tạo bầu không khí lung linh lãng mạn.',
  },
  {
    id: 'deco_menu_chalk',
    name: 'Bảng Menu Vẽ Phấn Nghệ Thuật',
    category: 'wall',
    icon: '📋',
    cost: 45000,
    cozyPoints: 15,
    bonusEffectDesc: '+8% tiền boa (Tip) từ khách hàng.',
    owned: false,
    equipped: false,
    description: 'Bảng vẽ tay xinh xắn ghi lại những món "best-seller" của quán.',
  },
  {
    id: 'deco_sofa',
    name: 'Ghế Băng Chờ Bọc Nhung Hồng',
    category: 'furniture',
    icon: '🛋️',
    cost: 85000,
    cozyPoints: 30,
    bonusEffectDesc: '+15% độ kiên nhẫn tối đa cho toàn bộ khách trong tiệm.',
    owned: false,
    equipped: false,
    description: 'Khách hàng có thể ngồi nghỉ chân thư giãn khi đợi món mang về.',
  },
  {
    id: 'deco_cat_painting',
    name: 'Tranh Treo Mèo Con Thưởng Trà',
    category: 'wall',
    icon: '🖼️',
    cost: 65000,
    cozyPoints: 22,
    bonusEffectDesc: 'Giảm 20% tốc độ tăng căng thẳng (Stress) cho nhân viên.',
    owned: false,
    equipped: false,
    description: 'Bức tranh dễ thương làm tan biến mọi mệt mỏi trong ca làm việc.',
  },
];

// === V0.4 - V0.5: ĐẾ CHẾ VỈA HÈ CATALOGS ===

export const BUSINESS_STAGES: Record<string, import('./types').BusinessStage> = {
  cart: {
    id: 'cart',
    name: 'Xe Đẩy Lề Đường',
    tagline: 'Khởi đầu bình dị với chiếc xe nhôm và ghế nhựa đỏ ven đường.',
    icon: '🛒',
    maxTables: 2,
    customerRateMs: 5500,
    cost: 0,
    requiredReputation: 0,
    description: 'Chỉ vỏn vẹn chiếc xe đẩy nhỏ nép bên vỉa hè, nhưng thơm nức mũi mùi pate bơ.',
  },
  corner: {
    id: 'corner',
    name: 'Góc Cây Me / Quán Cóc',
    tagline: 'Thêm dù che nắng mưa, quầy trà đá cà phê phin mát rượi.',
    icon: '🌳',
    maxTables: 3,
    customerRateMs: 4500,
    cost: 150000,
    requiredReputation: 25,
    description: 'Khách ngồi râm mát dưới bóng cây, tán gẫu chuyện thế thái nhân tình.',
  },
  awning: {
    id: 'awning',
    name: 'Tiệm Mái Hiên Bình Dân',
    tagline: 'Bảng hiệu bạt Hiflex sáng đèn, bàn xếp inox sạch sẽ.',
    icon: '🏮',
    maxTables: 4,
    customerRateMs: 3800,
    cost: 350000,
    requiredReputation: 60,
    description: 'Có mái hiên di động che kín, đón lượng khách đông đúc giờ cao điểm.',
  },
  eatery: {
    id: 'eatery',
    name: 'Quán Ăn Phố Lớn',
    tagline: 'Mặt tiền trung tâm, bếp mở hiện đại, thực khách xếp hàng.',
    icon: '🏪',
    maxTables: 5,
    customerRateMs: 3000,
    cost: 800000,
    requiredReputation: 120,
    description: 'Thương hiệu nức tiếng gần xa, ai ghé ngang qua cũng phải trầm trồ khen ngợi.',
  },
  empire: {
    id: 'empire',
    name: 'Chuỗi Đế Chế Vỉa Hè',
    tagline: 'Biểu tượng ẩm thực đường phố, chi nhánh phủ khắp phố phường!',
    icon: '👑',
    maxTables: 6,
    customerRateMs: 2400,
    cost: 2000000,
    requiredReputation: 250,
    description: 'Đỉnh cao của sự nghiệp ẩm thực vỉa hè, doanh thu tiền triệu mỗi ngày!',
  },
};

export const NEIGHBORS_DATA: Record<import('./types').NeighborId, import('./types').NeighborData> = {
  bac_ba: {
    id: 'bac_ba',
    name: 'Bác Ba',
    nickname: 'Tổ Trưởng Khu Phố',
    role: 'Tổ Trưởng Dân Phố',
    avatar: '👴',
    gender: 'male',
    favoriteDishId: 'cafe_sua',
    dialogues: {
      1: 'Vỉa hè buôn bán phải nhớ quét dọn sạch sẽ nha cháu! Đừng để rác bừa bãi kẻo lối xóm phiền lòng.',
      2: 'Cà phê của cháu pha đậm đà đấy! Bác đi tuần tra sáng nào cũng muốn ghé làm một ly cho tỉnh táo.',
      3: 'Bác nghe nói mấy bữa nữa có đoàn trật tự đô thị đi nhắc nhở. Cháu nhớ xếp bàn ghế gọn gàng nghe!',
      4: 'Cả xóm này ai cũng khen cháu chịu thương chịu khó. Bác đang tính xét tặng quán cháu danh hiệu Điểm Sáng Văn Hóa!',
      5: 'Cháu như con cháu trong nhà của bác vậy! Có ai làm khó cháu trên vỉa hè này, cứ bảo Bác Ba một tiếng!',
    },
    secrets: [
      {
        level: 2,
        title: 'Bí Mật Chiếc Sổ Tay Bác Ba',
        story: 'Bác Ba đã làm tổ trưởng hơn 20 năm, cuốn sổ tay cũ kỹ ghi chép sinh nhật của từng đứa trẻ trong xóm!',
      },
      {
        level: 4,
        title: 'Tấm Lòng Bác Tổ Trưởng',
        story: 'Ngày xưa Bác Ba từng là đầu bếp trong quân ngũ, nên bác sành ăn và rất quý những người nấu nướng có tâm.',
      },
    ],
    perkDescription: 'Bác Ba che chở: Giảm 50% nguy cơ bị nhắc nhở phạt lấn chiếm lề đường.',
  },
  co_bay: {
    id: 'co_bay',
    name: 'Cô Bảy',
    nickname: 'Bảy Vé Số May Mắn',
    role: 'Người Bán Vé Số Dạo',
    avatar: '👵',
    gender: 'female',
    favoriteDishId: 'banh_mi_trung',
    dialogues: {
      1: 'Mua giùm cô tờ vé số đi con ơi! Chiều nay 16h30 xổ số, biết đâu đổi đời trúng độc đắc tiền tỷ nhen!',
      2: 'Bánh mì trứng con chiên thơm phức hà. Cô đi bộ mỏi chân, ngửi mùi là muốn ghé ngồi nghỉ liền.',
      3: 'Sáng nay cô nghe mấy bà ngoài chợ đồn giá thịt heo với trứng sắp hạ nhiệt đấy, con tha hồ lấy hàng rẻ!',
      4: 'Cô để dành sẵn cho con cặp vé số có đuôi lộc phát 68 - 86 nè, chúc quán con hôm nay khách nườm nượp!',
      5: 'Con tốt bụng với cô quá! Cô coi con như con gái/con trai ruột vậy. Cầu trời phật phù hộ cho con buôn may bán đắt!',
    },
    secrets: [
      {
        level: 2,
        title: 'Ước Mơ Của Cô Bảy',
        story: 'Cô Bảy bán vé số suốt 15 năm qua để nuôi hai người con ăn học đỗ đại học trên thành phố.',
      },
      {
        level: 4,
        title: 'Tấm Vé Số Định Mệnh',
        story: 'Năm ngoái một vị khách quen mua vé của cô đã trúng giải an ủi 50 triệu và biếu lại cô một chiếc xe đạp mới.',
      },
    ],
    perkDescription: 'Vé số tài lộc: Mua vé số mỗi ngày và nhận cơ hội trúng giải thưởng lớn lúc 16:30!',
  },
  chu_nam: {
    id: 'chu_nam',
    name: 'Chú Năm',
    nickname: 'Năm Xe Ôm Biker',
    role: 'Tài Xế Công Nghệ & Xe Ôm',
    avatar: '🛵',
    gender: 'male',
    favoriteDishId: 'banh_mi_thit',
    dialogues: {
      1: 'Cho chú một ổ bánh mì thịt nhiều ớt với ly trà đá lẹ lẹ nha em trai, chú đang đợi nổ cuốc xe mới!',
      2: 'Bánh mì quán này ướp thịt nướng ngon số dách! Chú giới thiệu cả hội anh em tài xế ghé qua ủng hộ luôn rồi đó.',
      3: 'Chú chạy khắp hang cùng ngõ hẻm, thấy quán nào đông là biết ngay bí quyết. Quán cháu vừa rẻ vừa ngon, chắc chắn sẽ phất lên!',
      4: 'Trời sắp đổ mưa to đó cháu ơi, chuẩn bị kéo bạt che bàn kẻo khách ướt mem bây giờ!',
      5: 'Anh em tài xế bảo nhau: cứ thèm bánh mì là phải tạt vô quán này! Chú nhận ship đồ ăn độc quyền cho quán cháu luôn!',
    },
    secrets: [
      {
        level: 2,
        title: 'Chiếc Xe Máy Cổ',
        story: 'Chiếc xe Cup 50 chú Năm chạy là kỷ vật người cha để lại, bền bỉ qua hơn 30 năm mưa nắng vỉa hè.',
      },
      {
        level: 4,
        title: 'Hiệp Sĩ Đường Phố',
        story: 'Chú Năm từng nhiều lần giúp bà con bắt trộm và đưa người già lạc đường về tận nhà.',
      },
    ],
    perkDescription: 'Đội xe hỗ trợ: Tăng 20% tiền boa và nhận cảnh báo sớm trước khi thời tiết xấu ập tới.',
  },
  be_bong: {
    id: 'be_bong',
    name: 'Bé Bông',
    nickname: 'Học Sinh Lớp 3',
    role: 'Học Sinh Tiểu Học Trong Xóm',
    avatar: '👧',
    gender: 'female',
    favoriteDishId: 'tra_sua',
    dialogues: {
      1: 'Anh/Chị ơi, cho em xin một ly trà sữa trân châu thật nhiều thạch nha! Em để dành tiền ăn sáng cả tuần đó ạ!',
      2: 'Quán của anh/chị thơm quá chừng! Mỗi lần tan học đi ngang em đều nhìn hoài luôn.',
      3: 'Hôm nay em được điểm 10 môn toán nè! Mẹ thưởng cho em tiền mua bánh mì pate đặc biệt ăn mừng!',
      4: 'Em có vẽ tặng quán một bức tranh hình bánh mì cute nè, anh/chị dán lên xe đẩy nha!',
      5: 'Lớn lên em cũng muốn mở một tiệm bánh mì dễ thương như quán của anh/chị vậy á!',
    },
    secrets: [
      {
        level: 2,
        title: 'Heo Đất Tiết Kiệm Của Bông',
        story: 'Bé Bông có chú heo đất màu hồng, đang tiết kiệm tiền để mua quà sinh nhật tặng mẹ.',
      },
      {
        level: 4,
        title: 'Bức Tranh Giải Nhất Trường',
        story: 'Bức tranh vẽ quán vỉa hè của bạn đã đoạt giải Nhất hội thi vẽ nét đẹp quê hương cấp trường!',
      },
    ],
    perkDescription: 'Nụ cười thiên thần: Mang lại may mắn, tăng 15% lượng khách học sinh sinh viên ghé quán.',
  },
  chi_lan: {
    id: 'chi_lan',
    name: 'Chị Lan',
    nickname: 'Lan Văn Phòng Sành Ăn',
    role: 'Nhân Viên Công Sở Tòa Nhà Đối Diện',
    avatar: '👩‍💼',
    gender: 'female',
    favoriteDishId: 'banh_mi_dac_biet',
    dialogues: {
      1: 'Làm cho chị 1 ổ bánh mì đặc biệt mang đi nha, nhớ cắt đôi giùm chị, bọc giấy cẩn thận nhé.',
      2: 'Vỏ bánh mì giòn rụm mà pate thơm béo ngậy chuẩn vị Pháp luôn! Chị mê tít từ miếng cắn đầu tiên.',
      3: 'Hôm nay phòng Marketing tụi chị tăng ca, chị gom đơn 5 ổ bánh mì với 5 ly cà phê sữa đá cho cả nhóm nè!',
      4: 'Chị đã review 5 sao quán em lên nhóm "Hội Ăn Sạch Uống Lành Văn Phòng" rồi đấy, chuẩn bị đông khách nha!',
      5: 'Chị coi quán này như căn tin riêng của công ty vậy! Cứ đói là nghĩ ngay đến thương hiệu của em!',
    },
    secrets: [
      {
        level: 2,
        title: 'Food Blogger Giấu Mặt',
        story: 'Chị Lan ngoài làm công sở còn sở hữu một trang blog ẩm thực với hơn 50.000 lượt theo dõi!',
      },
      {
        level: 4,
        title: 'Hợp Đồng Cung Cấp Bữa Sáng',
        story: 'Chị Lan đã đề xuất ban giám đốc ký hợp đồng đặt bữa sáng cố định mỗi tuần từ quán vỉa hè của bạn.',
      },
    ],
    perkDescription: 'Khách sành điệu: Khách văn phòng tip hào phóng +25% tiền boa và thường xuyên gọi combo lớn.',
  },
};

export const DREAM_BOOK_NUMBERS = [
  { dream: 'Mơ thấy Con Rắn bò qua đường', number: '32', icon: '🐍' },
  { dream: 'Mơ thấy Con Chó vẫy đuôi', number: '11', icon: '🐕' },
  { dream: 'Mơ thấy Tiền rơi đầy ngõ', number: '52', icon: '💸' },
  { dream: 'Mơ được Crush tỏ tình ngọt ngào', number: '69', icon: '💖' },
  { dream: 'Mơ Trật Tự Đô Thị rượt chạy té khói', number: '88', icon: '👮' },
  { dream: 'Mơ Gà đẻ trứng vàng phát sáng', number: '28', icon: '🐓' },
  { dream: 'Mơ Xe Ôm nổ cuốc tiền triệu', number: '54', icon: '🛵' },
  { dream: 'Mơ Bánh Mì giòn rụm thơm bơ', number: '08', icon: '🥖' },
  { dream: 'Mơ Trúng Độc Đắc thành tỷ phú', number: '99', icon: '👑' },
  { dream: 'Mơ Bà bán bún bò đối diện làm hòa', number: '73', icon: '🍜' },
];

export const STREET_EVENTS: import('./types').StreetEvent[] = [
  {
    id: 'urban_patrol',
    title: '🚨 Công An & Trật Tự Đô Thị Đi Tuần!',
    tag: '👮 Trật Tự Đô Thị',
    icon: '🚓',
    description: 'Tiếng còi hú vang lên đầu hẻm kèm loa phát thanh: "Yêu cầu các hộ buôn bán lập tức dọn dẹp lòng lề đường!". Khách ngồi ăn nháo nhào nhìn bạn!',
    choices: [
      {
        text: 'Bê bàn ghế chạy thục mạng vào hẻm né đoàn xe',
        gainMoney: 0,
        gainReputation: -1,
        gainEnergy: -10,
        outcomeText: 'Pha né trạm đỉnh cao! Bạn và khách ôm ghế né vào ngõ cụt an toàn, dù hơi mệt nhưng cả xóm vỗ tay khen bạn nhanh như chớp!',
      },
      {
        text: 'Cầu cứu Bác Ba Tổ Trưởng ra đỡ lời bảo lãnh',
        gainReputation: 3,
        outcomeText: 'Bác Ba bước ra khoát tay: "Mấy chú thông cảm, cháu nó buôn bán ngoan ngoãn sạch sẽ lắm!". Đoàn kiểm tra mỉm cười gật đầu rồi đi tiếp. (+3 Uy tín)',
      },
      {
        text: 'Nghiêm chỉnh chấp hành nộp phạt tại chỗ (30,000 đ)',
        cost: 30000,
        gainReputation: 8,
        outcomeText: 'Đoàn lập biên bản nhắc nhở và tuyên dương tinh thần thượng tôn pháp luật! Hình ảnh quán văn minh được lan tỏa. (+8 Uy tín)',
      },
    ],
  },
  {
    id: 'gangster_protection',
    title: '🦹 Đại Ca Xăm Trổ Đòi Phí Bảo Kê Vỉa Hè!',
    tag: '🕶️ Giang Hồ Hẻm',
    icon: '🐉',
    description: 'Hai thanh niên đeo kính đen, tay xăm rồng phượng bước vào gõ bàn cồm cộp: "Khu này tụi tao bảo kê, biết điều đóng 40k tiền nước mỗi tuần đi chủ quán!"',
    choices: [
      {
        text: 'Tự tay làm 2 ổ Bánh Mì Thập Cẩm siêu cay mời đại ca hạ hỏa',
        cost: 12000,
        gainReputation: 5,
        gainEnergy: 5,
        outcomeText: 'Đại ca cắn một miếng cay xé lưỡi nhưng tấm tắc: "Má ơi ngon quá! Thôi từ nay tao bảo kê miễn phí cho quán mày, ai phá bảo tao!". (+5 Uy tín)',
      },
      {
        text: 'Gọi Chú Năm xe ôm hiệp sĩ đường phố ra nói chuyện lý lẽ',
        gainReputation: 3,
        outcomeText: 'Chú Năm dắt hội anh em biker mặt ngầu ra đứng khoanh tay lườm. Hai thanh niên đổi giọng "Tụi em ghé hỏi thăm sức khỏe thôi ạ" rồi lủi mất dạng!',
      },
      {
        text: 'Mở loa kẹo kéo bật Vinahouse quẩy cùng đại ca',
        gainReputation: 2,
        gainMoney: 25000,
        outcomeText: 'Nhạc sàn bốc lửa khiến đại ca hứng chí nhảy tưng bừng, bo ngược lại 25,000 đ tiền tip rồi rủ hôm nào đi hát karaoke! (+25,000 đ)',
      },
    ],
  },
  {
    id: 'cousin_borrow_money',
    title: '📱 Thằng Em Họ Bắn Tin Nhắn Vay Nóng Zalo!',
    tag: '💬 Người Nhà Báo Thủ',
    icon: '💸',
    description: 'Ting ting! Tin nhắn Zalo từ Em Họ: "Anh/Chị hai ơi! Em kẹt tiền nạp 4G với đóng tiền trọ quá, bắn em mượn 50,000 đ, cuối tuần có lương em trả liền hứa danh dự!"',
    choices: [
      {
        text: 'Chuyển khoản luôn 50,000 đ ("Coi như mất, nhưng thương em")',
        cost: 50000,
        gainMoney: 110000,
        gainReputation: 4,
        outcomeText: 'Bất ngờ chưa! Cuối tuần mẹ nó ở quê xách lên thùng gà ta với buồng chuối thơm lừng cảm ơn bạn, bạn đem chế biến bán được hẳn 110,000 đ! (+4 Uy tín)',
      },
      {
        text: 'Từ chối khéo: "Anh còn đang ăn bánh mì vụn chan nước tương đây em"',
        gainReputation: 0,
        outcomeText: 'Nó gửi lại một loạt sticker mèo khóc ròng than vãn rồi đi mượn người khác. Bạn bảo toàn nguyên vẹn số dư ví!',
      },
      {
        text: 'Rủ rê: "Qua phụ quán bưng bê rửa chén 1 buổi anh cho 60k bao ăn"',
        cost: 60000,
        gainEnergy: 30,
        gainReputation: 3,
        outcomeText: 'Nó lật đật chạy qua phụ cật lực, chén đĩa sạch bóng loáng, bạn đỡ mệt hẳn và hồi phục +30 Năng lượng!',
      },
    ],
  },
  {
    id: 'lotto_dream',
    title: '🎱 Chiêm Bao Thấy Giấc Mộng Số Đề Thần Kê!',
    tag: '🎲 Sổ Mơ Dân Gian',
    icon: '🐓',
    description: 'Đêm qua bạn nằm mơ thấy một con gà trống vàng bay qua xe bánh mì đẻ ra quả trứng phát sáng! Bà con trong xóm khuyên: "Gà đẻ trứng là số 28 hoặc 68 đó!"',
    choices: [
      {
        text: 'Xuống xác 20,000 đ ghi con số đề may mắn',
        cost: 20000,
        gainMoney: 120000,
        gainReputation: 3,
        outcomeText: 'Tài lộc nở rộ! Chiều xổ đúng phóc số chiêm bao! Bạn trúng đậm 120,000 đ tiền thưởng trong tiếng reo hò của cả xóm! (+120,000 đ)',
      },
      {
        text: 'Mua 1 tờ vé số 10k ủng hộ Cô Bảy lấy hên',
        cost: 10000,
        gainMoney: 30000,
        gainReputation: 2,
        outcomeText: 'Cô Bảy vui vẻ chúc phúc, bạn trúng giải an ủi nhận về 30,000 đ tiền may mắn!',
      },
      {
        text: 'Không mê tín dị đoan, tập trung nướng bánh mì',
        gainEnergy: 10,
        gainReputation: 1,
        outcomeText: 'Lao động là vinh quang! Bạn giữ vững tâm lý kiên định, nướng được mẻ bánh mì vàng ươm thơm nức mũi.',
      },
    ],
  },
  {
    id: 'crush_visit',
    title: '💖 Crush Bất Ngờ Xuất Hiện Tại Xe Bánh Mì!',
    tag: '✨ Rung Động Tuổi Trẻ',
    icon: '🥰',
    description: 'Crush đạp xe ghé vào tiệm: "Cho mình 1 ổ bánh mì trứng nhiều bơ patê nha...". Tim bạn đập thình thịch 150 nhịp/phút, chân tay bủn rủn!',
    choices: [
      {
        text: 'Run tay cho gấp đôi thịt phô mai & tặng kèm ly trà sữa',
        cost: 15000,
        gainReputation: 6,
        gainMoney: 30000,
        outcomeText: 'Crush ngạc nhiên thích thú: "Ôi sao đầy đặn thế này!". Crush khen bạn dễ thương và chủ động xin tài khoản Zalo / Instagram! (+6 Uy tín)',
      },
      {
        text: 'Dán giấy note thả thính: "Bánh mì thì có bơ, còn em thì có cơ hội không?"',
        gainReputation: 8,
        gainMoney: 20000,
        outcomeText: 'Crush đọc xong đỏ bừng mặt cười tít mắt, tip thêm cho bạn 20,000 đ và bảo "Sáng nào mình cũng ghé ủng hộ nha!". (+8 Uy tín)',
      },
      {
        text: 'Giữ vẻ mặt ngầu lạnh lùng, múa dao kẹp bánh mì như Salt Bae',
        gainReputation: 4,
        gainEnergy: 10,
        outcomeText: 'Thần thái đỉnh cao! Crush trầm trồ bấm máy quay story đăng lên mạng với caption: "Chủ quán bánh mì ngầu nhất phố!".',
      },
    ],
  },
  {
    id: 'qr_transfer_glitch',
    title: '💸 Biến Động Số Dư Tâm Linh: Khách Bắn 2k Thay Vì 20k!',
    tag: '📲 Drama Chuyển Khoản',
    icon: '🧾',
    description: 'Một bạn trẻ đi xe Vision sành điệu quét VietQR thanh toán 1 ổ đặc biệt rồi phóng vụt đi. Điện thoại ting ting: "Tài khoản vừa nhận +2,000 VND"!',
    choices: [
      {
        text: 'Hét lớn "Thiếu một số 0 bạn ơi!" rồi nhờ Chú Năm dí theo',
        gainMoney: 50000,
        gainReputation: 2,
        outcomeText: 'Chú Năm vít ga chặn đầu xe! Bạn trẻ ngượng chín mặt xin lỗi vì nhìn nhầm số 0, chuyển bù ngay 50,000 đ tạ lỗi! (+50,000 đ)',
      },
      {
        text: 'Chụp bill đăng lên Threads tâm sự Gen Z tìm người quen',
        gainMoney: 40000,
        gainReputation: 6,
        outcomeText: 'Bài viết viral 100k view! Cư dân mạng cười bò và rủ nhau kéo tới quán ăn bánh mì giải cứu chủ quán đáng thương! (+40,000 đ, +6 Uy tín)',
      },
      {
        text: 'Coi như của đi thay người, hoan hỷ bỏ qua lấy vía may',
        gainReputation: 3,
        gainMoney: 25000,
        outcomeText: 'Tâm sinh tướng! Ngay sau đó một vị khách hào sảng ghé mua và tip hẳn 25,000 đ vì thấy nụ cười hiền lành của bạn!',
      },
    ],
  },
  {
    id: 'trend_toptop',
    title: '🍋 Bắt Trend Tóp Tóp: Trà Chanh Giã Tay & Bánh Mì Chữa Lành!',
    tag: '🔥 Cơn Sốt Mạng Xã Hội',
    icon: '⚡',
    description: 'Trend mới bùng nổ trên TikTok! Cả đám đông học sinh sinh viên kéo tới đứng kín lề đường hỏi: "Quán có trà giã tay hay bánh mì chữa lành không ạ?"',
    choices: [
      {
        text: 'Cầm cối chày giã chanh đùng đùng phục vụ khách tới tấp',
        gainMoney: 85000,
        gainReputation: 5,
        gainEnergy: -20,
        outcomeText: 'Doanh thu bùng nổ rực rỡ thu về +85,000 đ! Dù hai cánh tay mỏi rã rời nhưng túi tiền rủng rỉnh ấm no! (+85,000 đ, +5 Uy tín)',
      },
      {
        text: 'Ra mắt món "Bánh Mì Chữa Lành Ôm Trọn Nỗi Đau" giá sinh viên',
        cost: 10000,
        gainMoney: 55000,
        gainReputation: 7,
        outcomeText: 'Cái tên độc lạ đánh trúng tim đen Gen Z! Các bạn trẻ check-in ầm ầm khen ngợi sự sáng tạo của bạn! (+55,000 đ, +7 Uy tín)',
      },
      {
        text: 'Kiên định bán bánh mì truyền thống không đu trend',
        gainReputation: 4,
        gainMoney: 20000,
        outcomeText: 'Các cô bác lớn tuổi trong xóm tấm tắc: "Ăn quán này mộc mạc chuẩn vị nhất, không màu mè!". (+4 Uy tín)',
      },
    ],
  },
  {
    id: 'delivery_bombed',
    title: '🛵 Bi Kịch Shipper: Bị Khách Bom 5 Ổ Bánh Mì Nóng Hổi!',
    tag: '😭 Bùng Đơn Oái Oăm',
    icon: '📦',
    description: 'Chú Năm giao hàng quay về mếu máo: Khách đặt 5 ổ bánh mì thập cẩm đặc biệt nhưng tới nơi thì thuê bao quý khách không liên lạc được!',
    choices: [
      {
        text: 'Treo bảng thanh lý nửa giá "Bánh mì giải cứu" cho sinh viên',
        gainMoney: 40000,
        gainReputation: 4,
        outcomeText: 'Các bạn sinh viên trường gần đó chạy ùa tới mua sạch trong 2 phút! Thu hồi vốn 40,000 đ và nhận ngàn lời cảm ơn! (+40,000 đ)',
      },
      {
        text: 'Mở tiệc liên hoan nội bộ cho toàn thể nhân viên ăn no nê',
        gainEnergy: 25,
        gainReputation: 3,
        outcomeText: 'Bé Mai, Em Tuấn, Bác Linh ăn giòn rụm tấm tắc khen ngon! Tinh thần làm việc phấn chấn x2, tốc độ phục vụ tăng vọt! (+25 Năng lượng)',
      },
      {
        text: 'Đem tặng các cô bác lao công và Bác Ba Tổ Trưởng',
        gainReputation: 9,
        outcomeText: 'Nghĩa cử cao đẹp làm ấm lòng khu phố! Bác Ba cảm động viết bài biểu dương quán trên bảng tin dân phố! (+9 Uy tín)',
      },
    ],
  },
  {
    id: 'neighbor_war',
    title: '👵 Đại Chiến Vỉa Hè: Bà Bán Bún Bò Đối Diện Hắt Nước Rửa Chén!',
    tag: '💥 Kịch Tính Xóm Giềng',
    icon: '🍜',
    description: 'Bà Năm bán bún bò bên kia đường thấy quán bạn đông khách bèn ghen tị, cố tình hắt xô nước rửa chén làm văng ra đường trước mặt thực khách!',
    choices: [
      {
        text: 'Bê ngay 1 đĩa bánh mì giòn nóng hổi sang mời bà Năm nếm thử',
        cost: 8000,
        gainReputation: 6,
        gainMoney: 30000,
        outcomeText: 'Lấy ân báo oán! Bà Năm ăn miếng bánh mì pate ngon quá bèn ngượng ngùng xin lỗi, sau đó hai quán bắt tay làm combo Bún Bò + Bánh Mì đắt hàng! (+30,000 đ)',
      },
      {
        text: 'Bật loa kẹo kéo hát bài Bolero trữ tình át tiếng cằn nhằn',
        gainReputation: 4,
        gainEnergy: 10,
        outcomeText: 'Giọng ca oanh vàng của bạn làm thực khách vừa ăn vừa vỗ tay cổ vũ rần rần! Bà Năm tắt đài dọn bàn đi vào nhà.',
      },
      {
        text: 'Mời Bác Ba Tổ Trưởng sang lập biên bản giữ gìn vệ sinh chung',
        gainReputation: 5,
        outcomeText: 'Bác Ba nghiêm khắc nhắc nhở bà Năm không được xả nước bừa bãi. Lòng lề đường lập tức thông thoáng sạch đẹp trở lại! (+5 Uy tín)',
      },
    ],
  },
  {
    id: 'multilevel_scam',
    title: '💼 Thanh Niên Đa Cấp "Tự Do Tài Chính 4.0" Rủ Làm Giàu!',
    tag: '👔 Làm Giàu Không Khó',
    icon: '💼',
    description: 'Một thanh niên mặc vest bảnh bao, cầm túi da bước vào: "Chào bạn, nhìn bạn nướng bánh mì cực khổ quá. Tham gia mạng lưới tài chính cùng tôi để sở hữu xe sang sau 3 tháng nhé!"',
    choices: [
      {
        text: 'Tặng luôn 1 ổ bánh mì ăn lót dạ: "Ăn đi em cho tỉnh táo rồi hẵng chém gió"',
        cost: 6000,
        gainReputation: 5,
        outcomeText: 'Thanh niên đói lả ăn một hơi hết sạch, rưng rưng nước mắt thú nhận bị lừa hết tiền và hứa sẽ từ bỏ đa cấp về quê làm lại từ đầu! (+5 Uy tín)',
      },
      {
        text: 'Hỏi dồn: "Thế dự án lãi bao nhiêu %, dòng tiền từ đâu ra?"',
        gainReputation: 3,
        gainMoney: 15000,
        outcomeText: 'Bị bạn chất vấn kinh tế học vi mô chuẩn bài, thanh niên ú ớ toát mồ hôi hột, vội vàng mua 1 ổ bánh mì rồi rút lui! (+15,000 đ)',
      },
      {
        text: 'Chỉ tay sang tiệm sửa xe Chú Năm: "Anh sang rủ Chú Năm đầu tư kìa"',
        gainReputation: 2,
        outcomeText: 'Chú Năm cầm cờ-lê ra hỏi thăm một câu là thanh niên xách cặp chạy té khói không dám quay lại!',
      },
    ],
  },
  {
    id: 'rain_shower',
    title: '🌦️ Cơn Mưa Rào Vỉa Hè Bất Chợt!',
    tag: '🌧️ Thời Tiết Phố Phường',
    icon: '🌧️',
    description: 'Bầu trời bỗng tối sầm và những giọt mưa rào lộp độp rơi xuống mặt đường. Bà con vội vã tìm chỗ trú mưa!',
    choices: [
      {
        text: 'Bung bạt dù che cho toàn bộ khách',
        cost: 15000,
        gainReputation: 4,
        gainMoney: 40000,
        outcomeText: 'Khách ấm lòng ngồi trú mưa, gọi thêm trà đá và cà phê nóng! (+40,000 đ doanh thu, +4 Uy tín)',
      },
      {
        text: 'Chỉ che xe đẩy, xin lỗi mời khách dọn vào hiên',
        gainReputation: 1,
        outcomeText: 'Khách thông cảm chia sẻ nỗi vất vả của hàng quán vỉa hè ngày mưa.',
      },
    ],
  },
  {
    id: 'market_sale',
    title: '🥬 Chợ Đầu Mối Giảm Giá Giờ Vàng!',
    tag: '🥦 Chợ Sỉ Giá Rẻ',
    icon: '🎉',
    description: 'Cô Ba tạp hóa quen ngoài chợ gọi điện: "Sáng nay lô pate và trứng gà tươi về nhiều quá, ghé lấy giá gốc nè cháu!"',
    choices: [
      {
        text: 'Tranh thủ lấy thêm lô bánh mì & trứng gà tươi giá sỉ',
        cost: 30000,
        gainReputation: 3,
        gainMoney: 50000,
        outcomeText: 'Kho hàng của bạn được bổ sung nguyên liệu tươi ngon với giá hời, tiết kiệm một khoản chi phí lớn! (+3 Uy tín)',
      },
      {
        text: 'Cảm ơn cô, hiện tại kho vẫn còn đủ dùng',
        gainReputation: 0,
        outcomeText: 'Bạn tiếp tục tập trung phục vụ thực khách.',
      },
    ],
  },
];

export const INITIAL_GAME_STATE: GameSaveState = {
  version: '0.4.0',
  playerId: 'player_default',
  shopName: 'Tiệm Bánh Mì Vỉa Hè Ba Miền 🥖',
  day: 1,
  gameTimeMinutes: 360, // 06:00 sáng
  money: 100000, // 100,000 VND vốn khởi nghiệp vỉa hè
  reputation: 10,
  player: {
    name: 'Chủ Quán Dễ Thương',
    energy: 100,
    maxEnergy: 100,
    cookingLevel: 1,
    cookingExp: 0,
  },
  inventory: {
    bread: 10,
    egg: 6,
    pork: 4,
    cucumber: 8,
    pate: 4,
    herb: 6,
    tea: 8,
    milk: 6,
    condensed_milk: 8,
    coffee: 8,
  },
  unlockedRecipes: ['banh_mi_trung', 'banh_mi_thit', 'banh_mi_dac_biet', 'tra_sua', 'cafe_sua'],
  purchasedUpgrades: {},
  hiredEmployees: [],
  employeeDetails: {},
  activeTheme: 'sakura_pink',
  ownedThemes: ['sakura_pink'],
  ownedDecorations: [],
  equippedDecorations: [],
  storageCapacity: 60,
  historySummaries: [],
  lastSavedAt: new Date().toISOString(),

  // Dữ liệu Đế Chế Vỉa Hè
  businessStage: 'cart',
  neighbors: {
    bac_ba: {
      level: 1,
      intimacyExp: 0,
      unlockedSecretIds: [],
      lastInteractedDay: 0,
    },
    co_bay: {
      level: 1,
      intimacyExp: 0,
      unlockedSecretIds: [],
      lastInteractedDay: 0,
    },
    chu_nam: {
      level: 1,
      intimacyExp: 0,
      unlockedSecretIds: [],
      lastInteractedDay: 0,
    },
    be_bong: {
      level: 1,
      intimacyExp: 0,
      unlockedSecretIds: [],
      lastInteractedDay: 0,
    },
    chi_lan: {
      level: 1,
      intimacyExp: 0,
      unlockedSecretIds: [],
      lastInteractedDay: 0,
    },
  },
  activeLotteryTicket: null,
  lotteryHistory: [],
  currentEvent: null,
  deliveryOrders: [],
  totalDeliveriesCompleted: 0,
};



