import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {useGameStore} from '../client/src/store/gameStore';
import {INITIAL_GAME_STATE,RECIPES} from '../shared/gameData';
import {simulatePassiveBranchTick} from '../shared/simulation/branches';
import {ActiveOrder} from '../shared/types';
let saved:string|null=null;
const fixture=()=>({id:'review-order',tableIndex:1,recipeId:'banh_mi_trung',typeId:'student',state:'waiting',patienceRemaining:45,maxPatience:45}) as ActiveOrder;
beforeEach(()=>{vi.useFakeTimers();saved=null;vi.stubGlobal('localStorage',{setItem:(_k:string,v:string)=>saved=v,getItem:()=>saved});vi.stubGlobal('fetch',vi.fn(async()=>({ok:false})));useGameStore.setState({gameState:structuredClone(INITIAL_GAME_STATE),activeOrders:[],dailyRevenue:0,dailyCost:0,dailyCustomersServed:0,dailyCustomersLost:0,deliveryOrders:[],activeModal:null,isShopOpen:false,isDailySummaryShown:false});});
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();});
it('probe: branch cash does not pay COGS',()=>{useGameStore.getState().recordBranchSales('banh_mi',30000,10000,'test');const g=useGameStore.getState().gameState;console.log('AUDIT_BRANCH',JSON.stringify({cashGain:g.money-INITIAL_GAME_STATE.money,cogs:g.dailyFinance?.cogs,inventoryUnchanged:JSON.stringify(g.inventory)===JSON.stringify(INITIAL_GAME_STATE.inventory)}));expect(g.money-INITIAL_GAME_STATE.money).toBe(30000);});
it('probe: delivery bypasses finance and price settings',()=>{const r=RECIPES.banh_mi_trung;useGameStore.setState(s=>({gameState:{...s.gameState,inventory:Object.fromEntries(r.requiredIngredients.map(id=>[id,10])),menuSettings:{banh_mi:{activeRecipes:['banh_mi_trung'],prices:{banh_mi_trung:999999}}}},deliveryOrders:[{id:'d',customerName:'test',recipeId:'banh_mi_trung',quantity:2,rewardMoney:r.basePrice*2,rewardTip:1000,timeRemainingSeconds:90,maxTimeSeconds:90,status:'pending'}]}));expect(useGameStore.getState().fulfillDeliveryOrder('d')).toBe(true);const s=useGameStore.getState();console.log('AUDIT_DELIVERY',JSON.stringify({runtimeRevenue:s.dailyRevenue,financeRevenue:s.gameState.dailyFinance?.revenue,financeCOGS:s.gameState.dailyFinance?.cogs}));expect(s.gameState.dailyFinance?.cogs).toBe(0);});
it('probe: entering the same branch clears guests',()=>{useGameStore.setState({activeOrders:[fixture()]});useGameStore.getState().switchActiveRestaurant('banh_mi');console.log('AUDIT_SWITCH',JSON.stringify({ordersRemaining:useGameStore.getState().activeOrders.length}));expect(useGameStore.getState().activeOrders).toHaveLength(0);});
it('probe: paying before cooking is accepted',()=>{useGameStore.setState({activeOrders:[fixture()]});const result=useGameStore.getState().collectPayment('review-order');console.log('AUDIT_EARLY_PAYMENT',JSON.stringify({accepted:result,cashGain:useGameStore.getState().gameState.money-INITIAL_GAME_STATE.money}));expect(result).toBe(true);});
it('probe: repeat liquidation pays without removing equipment',()=>{const s=useGameStore.getState();s.liquidateEquipment();s.liquidateEquipment();console.log('AUDIT_LIQUIDATION',JSON.stringify({cashGain:useGameStore.getState().gameState.money-INITIAL_GAME_STATE.money,levels:useGameStore.getState().gameState.purchasedUpgrades}));expect(useGameStore.getState().gameState.money-INITIAL_GAME_STATE.money).toBe(4000000);});
it('probe: event income counted twice in end-day profit',()=>{useGameStore.setState(s=>({gameState:{...s.gameState,inventory:{}}}));useGameStore.getState().triggerSurpriseIncident({id:'audit',title:'test',description:'test',icon:'',moneyChange:100000,reputationChange:0} as any);useGameStore.getState().resolveSurpriseIncident();useGameStore.getState().endDayAndSleep();const g=useGameStore.getState().gameState;console.log('AUDIT_EVENT_PNL',JSON.stringify({cashChange:g.money-INITIAL_GAME_STATE.money,netProfit:g.historySummaries[0].netProfit}));expect(g.historySummaries[0].netProfit).toBe(185000);});
it('probe: spoilage is both inventory loss and additional cash charge',()=>{vi.spyOn(Math,'random').mockReturnValue(.5);useGameStore.setState(s=>({gameState:{...s.gameState,inventory:{pork:100},restaurantInventories:{banh_mi:{pork:100}}}}));useGameStore.getState().endDayAndSleep();const g=useGameStore.getState().gameState;console.log('AUDIT_SPOILAGE',JSON.stringify({cashChange:g.money-INITIAL_GAME_STATE.money,spoilageCost:g.historySummaries[0].spoilageCost,activeInventory:g.inventory.pork,branchInventory:g.restaurantInventories?.banh_mi?.pork}));expect(g.restaurantInventories?.banh_mi?.pork).toBe(100);});
it('probe: active operating-day runtime counters are not saved',()=>{useGameStore.setState({dailyRevenue:100000,activeOrders:[fixture()],dailyCustomersServed:4});useGameStore.getState().saveLocal();const data=JSON.parse(saved!);console.log('AUDIT_SAVE',JSON.stringify({savedRuntimeRevenue:data.dailyRevenue,savedFinanceRevenue:data.dailyFinance?.revenue,savedOrders:data.activeOrders}));expect(data.dailyRevenue).toBeUndefined();});
it('probe: high branch prices do not reduce served customers',()=>{vi.spyOn(Math,'random').mockReturnValue(.5);const params={restaurantId:'banh_mi' as const,branchLevel:1,branchStaff:[],activeRecipes:['banh_mi_trung' as const]};const normal=simulatePassiveBranchTick(params)!;const high=simulatePassiveBranchTick({...params,playerPrices:{banh_mi_trung:1800000}})!;console.log('AUDIT_PRICE_DEMAND',JSON.stringify({normal,high}));expect(high.servedCustomers).toBe(normal.servedCustomers);expect(high.earnedRevenue/normal.earnedRevenue).toBeCloseTo(100);});
it('probe: ticking time overwrites a newly spawned street event',()=>{vi.spyOn(Math,'random').mockReturnValue(0);useGameStore.setState(s=>({isShopOpen:true,dailyEventsCount:0,lastEventTimeMinutes:0,gameState:{...s.gameState,currentEvent:null,gameTimeMinutes:360}}));useGameStore.getState().tickTime(1.25);const s=useGameStore.getState();console.log('AUDIT_EVENT_TICK',JSON.stringify({events:s.dailyEventsCount,modal:s.activeModal,event:s.gameState.currentEvent}));expect(s.dailyEventsCount).toBe(1);expect(s.gameState.currentEvent).toBeNull();});
it('probe: overnight leaves unfinished guests in next day',()=>{useGameStore.setState({activeOrders:[fixture()]});useGameStore.getState().endDayAndSleep();console.log('AUDIT_OVERNIGHT_ORDERS',JSON.stringify({day:useGameStore.getState().gameState.day,orders:useGameStore.getState().activeOrders.length}));expect(useGameStore.getState().activeOrders).toHaveLength(1);});


